version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ppt
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: elections_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data:
